[tool.black]
line-length = 88
exclude = '''
/(
  \.venv
| build
| dist
| \.git
)/
'''

[tool.isort]
profile = "black"
line_length = 88
skip = [".venv","build","dist",".git"]

[tool.pytest.ini_options]
addopts = "-q --disable-warnings"
testpaths = ["tests"]
